(VAD_p396) PS C:\Users\User\Documents\repos\SHIBAL> python .\train_custom_e2e.py

=== 설정 정보 ===
데이터:
  - 훈련: custom_data/original_images_train.txt
  - 검증: custom_data/original_images_valid.txt
  - 테스트: custom_data/original_images_test.txt
  - 모델: saved_models/888tiny.pkl
훈련:
  - 모델: tiny
  - 배치 크기: 16
  - 학습률: 0.0001
  - 최대 에포크: 50
  - 드롭아웃: 0.4
GPU:
  - 멀티 GPU: True
  - GPU ID: [0, 1]
[GPU] 2개 GPU 사용: [0, 1]
  GPU 0: NVIDIA GeForce RTX 4090 (24.0GB)
  GPU 1: NVIDIA GeForce RTX 4090 (24.0GB)
[E2E] 33298개 이미지 로드됨
[E2E] 정상: 21781개, 비정상: 11517개
[E2E] 4756개 이미지 로드됨
[E2E] 정상: 3111개, 비정상: 1645개
[E2E] 9515개 이미지 로드됨
[E2E] 정상: 6224개, 비정상: 3291개
훈련 데이터: 33298개
검증 데이터: 4756개
테스트 데이터: 9515개
[OK] STEAD 모델 부분 로드: saved_models/888tiny.pkl
[GPU] DataParallel 활성화 (GPU [0, 1] 병렬)

=== End-to-End 훈련 시작 ===
Epoch 0:   0%|                                                                                                                                                                                            | 0/2082 [00:01<?, ?it/s]
전체 진행률:   0%|                                                                                                                                                                                          | 0/50 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\User\Documents\repos\SHIBAL\train_custom_e2e.py", line 635, in <module>
    main()
  File "C:\Users\User\Documents\repos\SHIBAL\train_custom_e2e.py", line 562, in main
    train_loss = train(train_loader, model, optimizer, scheduler, device, epoch, use_multi_gpu)
  File "C:\Users\User\Documents\repos\SHIBAL\train_custom_e2e.py", line 334, in train
    if outputs.dim() == 1:
AttributeError: 'tuple' object has no attribute 'dim'
